Bentheburrito/sacastats

priv/static/js/flex-bootstrap-table.js
Just a small quick fix to call the resort every time a search is done.
=> Fixed search sort issue.

lib/sacastats_web/templates/layout/root.html.heex
Made front-facing text for character endpoint to be singular.
This will close #28
=> Character Endpoint Spelling Correction

priv/static/css/character/general.css
Again pretty simple. Removed a random margin that was being applied to `#characterGeneral`. The file was also reformatted.
This will close #29.
=> Removed unneeded margin from #characterGeneral

lib/sacastats_web/templates/character/template.html.heex, lib/sacastats_web/templates/layout/root.html.heex, priv/static/css/navbar-events.css, priv/static/css/styles.css
This is pretty self-explanatory, but the navbar should be working properly now. I also externalized the navbar styles into a new `navbar-events.css` file to make debugging easier.
This will close #15.
=> Fixed nav stuttering and other nav styling issues

lib/sacastats/census_cache.ex, test/sacastats/census_cache_test.exs
At this point the cache is not very census-specific, so if our needs start to outgrow this impl, we'll probably use a proper library like Cachex.
=> Rework how the fallback function is passed/used.

lib/sacastats_web/templates/layout/root.html.heex
Added needed moving-nav-link-container class for Character endpoint.
This will close #71
=> Navbar fix 2

lib/sacastats.ex, lib/sacastats/application.ex, lib/sacastats/census_cache.ex, lib/sacastats/census_cache/fallbacks.ex, lib/sacastats_web/controllers/character_controller.ex, lib/sacastats_web/router.ex, lib/sacastats_web/templates/character/general.html.heex, lib/sacastats_web/templates/character/session.html.heex, lib/sacastats_web/templates/character/sessions.html.heex, lib/sacastats_web/templates/character/template.html.heex, lib/sacastats_web/templates/character/weapons.html.heex, lib/sacastats_web/views/character_view.ex
Huge refactoring of character controller and assigns to be cleaner (and hopefully easier to read). Let me know if you have any suggestions to further improve this in terms of naming, where things go, etc. This will close #58
=> Character Controller cleanup

lib/sacastats_web.ex, lib/sacastats_web/templates/layout/root.html.heex
The title of the site now depends on the endpoint itself.
This will close #62.
=> Dynamic Site Title

lib/sacastats/utils/utils.ex, lib/sacastats_web/controllers/character_controller.ex, lib/sacastats_web/templates/character/weapons.html.heex, priv/static/css/character/weapons.css, priv/static/css/flex-bootstrap-table-selection.css, priv/static/css/flex-bootstrap-table.css, priv/static/js/flex-bootstrap-table.js
Added some more interesting columns to view.
Added pagination to the top as well as the bottom. The row cap per page is now 100. And now when you change pages it will scroll back up to the top of the table. 
This will close #44
=> Weapon table v2.6

lib/sacastats_web/templates/character/template.html.heex, priv/static/css/navbar-events.css
Subnavbar styles are now working properly on both mobile and desktop.
This will close #77
=> Fixed subnavbar styles

priv/static/css/bootstrap-override.css
It is no more!
This will close #81
=> Got rid of bootstrap map warning

lib/sacastats_web/templates/layout/root.html.heex, lib/sacastats_web/templates/page/index.html.heex, priv/static/css/index.css, priv/static/css/styles.css
- I pushed the initial website release to June 15th (My 9th year PS2 anniversary lol) Hopefully this will work for you.
- I also cleaned up some styling that looked a bit strange and removed unused navigation.
- For the outfit polls instead of removing them from the home page I just put "coming soon"
Should there be a 404 page btw?
This will close #89
=> Alpha site pass

lib/sacastats/scripts/get_weapons.exs, lib/sacastats/static_data/weapons.json
=> Update image defaults

priv/static/js/character/model.js
MAX base should now be rendering properly.
This will close #101
=> MAX should always be capitalized

priv/static/js/flex-bootstrap-table-filter.js
Added an undefined check when auto-selecting inputs.
This will close #115
=> Fixed Filter NPE

lib/sacastats/schemas/discord_user.ex, lib/sacastats/schemas/poll.ex, lib/sacastats_web/controllers/page_controller.ex, lib/sacastats_web/discord_auth.ex, lib/sacastats_web/endpoint.ex, lib/sacastats_web/live/poll_live.ex, lib/sacastats_web/live/poll_live/view.ex, lib/sacastats_web/templates/layout/root.html.heex, lib/sacastats_web/templates/page/account.html.heex, lib/sacastats_web/views/poll_view.ex, mix.exs, priv/repo/migrations/20220707024346_add_discord_user.exs
It needed revisiting - should work the exact same from the user's perspective.
We store discord users in the DB now so it's easier to reference who voted in polls.
=> Custom Discord OAuth2 Reimplementation

lib/sacastats/application.ex, lib/sacastats/census_cache.ex, lib/sacastats/census_cache/fallbacks.ex, lib/sacastats/characters.ex, lib/sacastats/conversions.ex, lib/sacastats/schemas/session.ex, lib/sacastats/scripts/get_weapons.exs, lib/sacastats/static_data/weapons.json, lib/sacastats/utils/static_data.ex, lib/sacastats/utils/utils.ex, lib/sacastats/weapons.ex, lib/sacastats_web/controllers/character_controller.ex, lib/sacastats_web/router.ex, lib/sacastats_web/templates/character/general.html.heex, lib/sacastats_web/templates/character/template.html.heex, lib/sacastats_web/templates/character/weapons.html.heex, lib/sacastats_web/templates/character/weapons_not_found.html.heex
I moved all the helper fns in CharacterControllers to new helper/context modules, `SacaStats.{Characters, Conversions, Weapons}` and optimized some of them (lmk if you have questions!). I made a bunch of other changes, like consolidating our two `maybe_to_int` fns into one under `Utils`.
Visit all pages (especially the character ones), make sure all content looks correct
=> Codebase Cleanup pass (CharacterController)

priv/static/js/flex-bootstrap-table-filter.js
Fixed the NPE that would occur from time to time.
This will close #124
=> Removed NPE

lib/sacastats.ex, lib/sacastats_web/views/character_view.ex
This is a prospective fix that will close #148. I don't actually have a session on hand with a snowman kill so let me know if this fixes it for you @dm0896665 
Also wrapped the login/logout messages in `<li>` to be consistent with the other messages.
=> Fix crash for "Snowman kill by squad member" xp

lib/sacastats/schemas/session.ex, lib/sacastats_web/controllers/character_controller.ex, lib/sacastats_web/router.ex
Created a new `/latest` endpoint for the character's sessions
Ex. `/character/dndmackey/sessions/latest`
This will be good for always being able to keep the same link and use it multiple times to find what the user usually will try to get when it comes to sessions.
This will close #144
=> Latest session

lib/sacastats_web/templates/character/template.html.heex, lib/sacastats_web/templates/layout/root.html.heex, priv/static/css/character/template.css, priv/static/css/navbar-events.css
Character name overflow has been changed to ellipsis. 
This will close #145.
=> Removed overflow for long character names

assets/js/app.js, assets/src/formats.ts, lib/sacastats_web/live/character_live/search.ex, lib/sacastats_web/live/session_live/view.ex, lib/sacastats_web/templates/character/general.html.heex, lib/sacastats_web/templates/character/session.html.heex, lib/sacastats_web/templates/character/template.html.heex, lib/sacastats_web/views/character_view.ex
This PR should fix the unformatted dates on new/updated elements, closing #140. I refactored a bit of the TS formatting code, so let me know if it looks okay.
I had some trouble using `push_event` with the `phx:...` listeners, since the TypeScript `Event` type doesn't have the `detail` property that Phoenix adds (so the compiler got mad). So I used a Hook instead
=> Fix unformatted dates on LiveViews 
